### ISSUE TITLE
Publish source code

### ISSUE THREAD

**Issue by ammario** [ahertel/wholefoods-delivery-slot-finder#1]
Thanks for publishing this!

Please publish the source code as well.

**Comment by ahertel** [comment]
Hi Ammario! Thanks for your interest. The .scpt file _is_ the source code, if I’m understanding your request correctly. If you download it and open it with AppleScript.app, you can read and modify the code. If there is another way you’d like me to share the source code, let me know!

**Comment by ahshabbir** [comment]
If you can publish the code in a .txt file that'd be ideal, as the .scpt file cannot be properly read without the AppleScript application.

**Comment by ahertel** [comment]
Published a copy of the code in .txt format.
Why do you want it in another format btw. It seems to me that if you don't have the AppleScript application you can't run the code, so it's not very useful to you. Thanks!

**Comment by ahertel** [comment]
I just replaced the .txt copy to .applescript
you should still be able to view the contents easily from GitHub.com or with any text editor.
Would still love to know the answer to my question above.

**Comment by ahshabbir** [comment]
I felt like having a viewable copy of the file before others download it would make others more comfortable with using your script given the added transparency. Additionally, since I've coded in Applescript before, I could potentially find a way to bring the program to other platforms as well.

**Comment by ahertel** [comment]
Makes sense. Thanks for explaining
