### ISSUE TITLE
keep getting unknown page encountered after start

### ISSUE THREAD

**Issue by bluerainsky** [ahertel/wholefoods-delivery-slot-finder#14]
Followed the instructions and opened the checkout page and confirmed it is a compatible page, but every time I run the script, after a few seconds the Unknown Page Encountered error pops up.

**Comment by karenpeng** [comment]
same here

**Comment by ahertel** [comment]
Hi @bluerainsky. thanks for your message. Would you mind downloading the latest version of the code and reading the updated instructions(including the compatibility section). Then try to run it and let me know if you still have this issue. If you do, we'll resolve it together

**Comment by bluerainsky** [comment]
Just checked, turns out that my checkout page is one with the delivery type option (one of the incompatible one). Thanks for checking, hope to get the compatible update soon.

**Comment by ahertel** [comment]
@bluerainsky thanks for the update!! Glad we figured it out. At the moment I have to focus on my job search so I don't have much time to expand the region compatibility. But I may have time in the future, or others might contribute lend a hand. You can subscribe to notifications for  issue #12 to keep track of any progression this.
