### ISSUE TITLE
"User Canceled" Error

### ISSUE THREAD

**Issue by Methodman1** [ahertel/wholefoods-delivery-slot-finder#15]
Hi, thanks a lot for putting this script together.  When I try to run it, I'm getting the message: 
error "User canceled." number -128 from «script» to item

I believe I followed all the right steps.  Did I miss something?

Thanks!

**Comment by RyannosaurusWrecks** [comment]
Getting that same error - can't figure out how to get past it.

**Comment by JustinKayy** [comment]
Same issue here. I go through all the prompts. The last prompt asks me if I want to receive an SMS notification, where I click no and the script says "user canceled."

**Comment by bbaker6225** [comment]
+1 for this issue

**Comment by ahertel** [comment]
@Justin-K @bbaker6225 @Methodman1 @RyannosaurusWrecks  sorry for the trouble. I made a silly mistake during my late night coding sesh yesterday. should be fixed now. Please let me know. Thanks!

**Comment by BrightMG** [comment]
Working for me now, thanks!

**Comment by Methodman1** [comment]
Looks good now, thank you!!

**Comment by JustinKayy** [comment]
@ahertel It's working, thank you.
