### ISSUE TITLE
[enhancement] auto-confirm out of stock

### ISSUE THREAD

**Issue by wardnath** [ahertel/wholefoods-delivery-slot-finder#3]
Hey @ahertel, thank you so much for making this project. I'm really liking the script. One thing that keeps happening is one of my items will go out of stock and I will manually have to delete the item and confirm. Due to how often things go out of stock I just deal with this by buying 4 different versions of the same thing assuming 3 out of 4 things will be gone. 

- Would this feature be valuable?
- How could someone choose to enable this feature or not? Dialogue box on startup maybe?

I can help with building this feature if that would be of use.

**Comment by ahertel** [comment]
Hi @wardnath ! Yes, I ran into those out of stock issues pages countless times too so I actually briefly tried building an "auto-confirm out of stock" feature myself, but I couldn't figure out how to get the program to click the "Continue" button. I had found this [code](http://www.cubemg.com/how-to-click-a-button-on-a-web-page-with-applescript/) which has to do the actual clicking,  but I couldn't figure out which tag/id/name etc to pass to the click() function. I don't really know my way around HTML yet. I was planning on taking another stab at this feature myself in the coming days, but if you want to build that feature, that'd be great. I'd be happy to merge it into the current tool.

Once the program can click buttons on Amazon's website, I was planning on adding and auto-checkout feature: Once slots appear, the script could automatically select the first available one, and then click continue to finish the order. However, sometimes a slot appears, but by the time you select it and click "continue" it's already full and the continue button stops working. So in that case the program would keep refreshing, selecting new time slots, trying to checkout until the order finally goes through and the order confirmation page appears. This would make the tool complete in my eyes as it would then be fully autonomous and could even place orders while one is sleeping haha. I think once we having the auto-confirm out of stock clicking figured out, it would pretty easy to add this auto-checkout feature.

Lastly, I agree that a dialog box would a good way of prompting the user if they want to enable these autonomous two features(auto-confirm out of stock, and auto-checkout).

**Comment by donoka** [comment]
The above mentioned ideas would be fantastic to have in the script. 
Thank you so much for making this @ahertel, in some ways truly a life saver. 
Successfully used it yesterday morning and will continue using it.

**Comment by wardnath** [comment]
Thanks for the quick reply @ahertel! I've worked with automated click actions via selenium and puppeteer before but I'm new to apple script. I'll give it a look though. 

definitely having some kind of confirmation on launch would be good. If someone has some items they really don't want to be without they may prefer to not go through with the order. I would assume that most people just would want to auto confirm though

**Comment by ahertel** [comment]
@wardnath I think I got the _auto-confirm out of stock_ feature to work. Just testing it to make sure it's reliable. It was actually surprisingly easy. I had just been using the wrong code snippet from the [CubeMG page](http://www.cubemg.com/how-to-click-a-button-on-a-web-page-with-applescript/). Will keep you posted.

**Comment by ahertel** [comment]
@wardnath @donoka After some more testing, I feel confident the new _auto-ignore out of stock_ feature works reliably so I updated the master branch. Let me know if it works for you / what you think.

The automatic slot selection and checkout feature have proven far more difficult. More specifically, I ran into a roadblock: Once my script finds a slot, I can't even manually select it in Safari on my computer so I get stuck on that page, no matter how many times I refresh. To ensure it wasn't an out of stock issue, I loaded the checkout page in Google Chrome, and was repeatedly able to select a slot and finishing checkout out. I am also able to select a slot in Safari on a different MacBook in my house. Either something is wrong with my laptop's Safari, or perhaps Amazon has flagged my laptop's Safari client on my specific laptop due to my constant refreshing.  
Am curious to hear your thoughts. Thanks

EDIT: I create a new issue #6 to discuss this feature

**Comment by changethisusername** [comment]
This might be the time where we start using a VPN to make sure the computers don’t get flagged as bots, or if they do it’s only temporary. Let’s hope the “ban” is not connected to the amazon account.

**Comment by ahertel** [comment]
@Dhosting it hasn't put a block on my Amazon account as the script seems to run well on another Mac I have in the house. I tweaked my Safari cookie settings and uninstalled my adblocker. I suspect that this is culprit, not Amazon flagging my computer. But I have yet to confirm. Will update once I do.
A VPN is a good suggestion. Perhaps that will become necessary. If you have been having issues with this tool that were solved by using a VPN, let me know.

**Comment by ahertel** [comment]
@donoka @wardnath would love your thoughts on the auto-ignore out of stock feature if have the time. Has it worked for you? Thanks!

**Comment by wardnath** [comment]
Thanks for adding in the feature @ahertel! I’ll try it next time I do an order. This project has been so helpful.

**Comment by wardnath** [comment]
Update @ahertel, it works great! I noticed I had to give permissions to allow the script to click for me. Other than that it worked fine. 

<img width="420" alt="Screen Shot 2020-04-05 at 7 11 07 PM" src="https://user-images.githubusercontent.com/4514195/78554299-e6f9e700-77d8-11ea-926a-4a8503b67f35.png">

**Comment by ahertel** [comment]
@wardnath glad it worked! and yes, permissions are necessary. To prevent users from encountering that error I added a popup in my latest update telling users to enable these permission before they can continue with the script. If you download the latest version you should see the relevant prompt.

**Comment by wardnath** [comment]
Awesome work @ahertel
