### ISSUE TITLE
Thanks for doing this! for me, doesn't seem to load - could it be related to safari experimental feature?

### ISSUE THREAD

**Issue by mbbb22** [ahertel/wholefoods-delivery-slot-finder#44]
Fixed it!

**Comment by ahertel** [comment]
@mbbb22 Hope you are and your family and safe and well. Great to hear you figured it out. What was the resolution - perhaps I need to fix something?

Sorry I couldn't get back to you myself. My inbox has been blowing up since the CNBC article about this went live.

**Comment by mbbb22** [comment]
Hey there!

Thank you! We are safe just NYC is overburdened with everyone trying to get food… as you know… 
The issue was my error — I didn’t hit the run button on the script!  So far I’ve had two time slots notifications but no success… but hoping one will work.  

I wish I knew people I could refer you to for work once you graduate but I don’t know anyone. However, I’m sure you’ll have no problem finding work!

Stay safe and thank you so much for providing a very helpful service. 

Meri
