### ISSUE TITLE
PrimeNow?

### ISSUE THREAD

**Issue by Merculis** [ahertel/wholefoods-delivery-slot-finder#51]
Would it be possible to extend this to PrimeNow?

**Comment by jazaval** [comment]
Opened #50 to support Prime Now. You can use my [fork](https://github.com/jazaval/Amazon-Fresh-Whole-Foods-delivery-slot-finder/tree/primenow-support) in the meantime for Prime Now support - let me know how it goes!

**Comment by Mikri2005** [comment]
Ah, this is what I came here to ask.  Thank you so much!

**Comment by Merculis** [comment]
> Opened #50 to support Prime Now. You can use my [fork](https://github.com/jazaval/Amazon-Fresh-Whole-Foods-delivery-slot-finder/tree/primenow-support) in the meantime for Prime Now support - let me know how it goes!

You're the man!  The fork worked perfectly!
