### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by bsteinlo** [ahertel/wholefoods-delivery-slot-finder#9]
If I open the minimized Safari window, after 30 seconds it quits and I get the following error

error "Safari got an error: Can’t get window id 6178." number -1728 from window id 6178

**Comment by ahertel** [comment]
hi @bsteinlo. Would love to help you figure this out and sorry to hear it hasn't been more straightforward for you. When the script starts, it opens a new Safari window and then minimizes it to hide it while it runs. Is it possible that you are closing a tab in that window, or closing the window entirely, or quitting Safari?
The window launched by the script stars with two tabs: one empty/default tab, and the delivery slot page. The script then close the right most tab (the delivery slot one), and reopens a new tase with the same URL after 10 seconds. the left most tab(empty/default) should never be closing.
Let know if you are seeing different behavior

**Comment by ahertel** [comment]
@bsteinlo I take it your problem was resolved?
